export const SAMPLE_TYPE = 'SAMPLE_TYPE'

export const SET_HOME_FILTER1 = 'SET_HOME_FILTER1'
export const SET_HOME_FILTER2 = 'SET_HOME_FILTER2'
export const SET_KEYWORD = 'SET_KEYWORD'
export const ADD_KEYWORD = 'ADD_KEYWORD'
export const FETCH_NEXT_PAGE = 'FETCH_NEXT_PAGE'

export const SHOW_MODAL = 'SHOW_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'
export const SET_IMGSRC = 'SET_IMGSRC'

export const SET_FAVORITE = 'SET_FAVORITE'
export const ADD_FAVORITE = 'ADD_FAVORITE'
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE'

export const SHOW_ADDITIONAL = 'SHOW_ADDITIONAL'
export const HIDE_ADDITIONAL = 'HIDE_ADDITIONAL'

export const SHOW_LOGIN = 'SHOW_LOGIN'
export const HIDE_LOGIN = 'HIDE_LOGIN'

export const SHOW_SUGGEST = 'SHOW_SUGGEST'
export const HIDE_SUGGEST = 'HIDE_SUGGEST'