// Home
export const FETCH_NEW_RCMD = 'FETCH_NEW_RCMD'

// Popular
export const SET_POP_FILTER = 'SET_POP_FILTER'

export const SET_FAVORITE = 'SET_FAVORITE'
export const ADD_FAVORITE = 'ADD_FAVORITE'
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE'

export const SHOW_SUGGEST = 'SHOW_SUGGEST'
export const HIDE_SUGGEST = 'HIDE_SUGGEST'

export const FETCH_DETAIL_EMOTICON = 'FETCH_DETAIL_EMOTICON'

export const SET_CATE_SIDE_TAB = 'SET_CATE_SIDE_TAB'
export const TOGGLE_CATE_SELECTED = 'TOGGLE_CATE_SELECTED'
export const SET_CATE_SIDE_SEARCH = 'SET_CATE_SIDE_SEARCH'